### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by jiangdaniel** [jiangdaniel/dl-papers#2]
- [x] Sanity check everything
- [ ] GPU implementation
- [x] Visualize weight matrix samples
- [ ] Sample different weight matrix for each data point?
- [x] Figure out values for number of gaussians
- [x] Figure out size of local sampling regions
